http:
  middlewares:
    audit-forward:
      forwardAuth:
        address: "http://audit-service:8080/ingest"
        trustForwardHeader: true

  routers:
    example:
      entryPoints:
        - web
      rule: "PathPrefix(`/example`)"
      service: example-service
      middlewares:
        - audit-forward

    core-auth:
      entryPoints:
        - web
      rule: "PathPrefix(`/auth`)"
      service: core-auth-service
      middlewares:
        - audit-forward

    pet-management:
      entryPoints:
        - web
      rule: "PathPrefix(`/animals`)"
      service: pet-management-service
      middlewares:
        - audit-forward

    adoption-ai:
      entryPoints:
        - web
      rule: "PathPrefix(`/adoption`)"
      service: adoption-ai-service
      middlewares:
        - audit-forward

    godparenthood:
      entryPoints:
        - web
      rule: "PathPrefix(`/godparenthood`)"
      service: godparenthood-service
      middlewares:
        - audit-forward

    audit:
      entryPoints:
        - web
      rule: "PathPrefix(`/audit`)"
      service: audit-service

  services:
    example-service:
      loadBalancer:
        servers:
          - url: "http://example-module:3005"

    core-auth-service:
      loadBalancer:
        servers:
          - url: "http://piaca-core-auth:3001"

    pet-management-service:
      loadBalancer:
        servers:
          - url: "http://piaca-pet-management:3002"

    adoption-ai-service:
      loadBalancer:
        servers:
          - url: "http://piaca-adoption-ai:3003"

    godparenthood-service:
      loadBalancer:
        servers:
          - url: "http://piaca-godparenthood:3004"

    audit-service:
      loadBalancer:
        servers:
          - url: "http://audit-service:8080"
